### ISSUE TITLE
Bug in constraints

### ISSUE THREAD

**Issue by csegura1983** [d9w/WindFLO#6]
The constraints are not checked correctly in the server and/or locally. For instance, the positions of the turbines can be negative and/or lager than the width or height of the scenario and the solution is still valid. For instance, in my exection with ID 1507, a set of 2000 turbines were placed with the following code:

  vector < pair < double, double > > test;
  for (int i = -1000; i < 1000; i++){
    test.push_back(make_pair(100000 + i * 300000, 100000 + i * 200000));
  }

This gives a very low fitness and with this solution I am placed in the first position. However, the solution is not valid. It seems that in other solutions of other participants this situation is arising.

Regards,
   Carlos Segura

**Comment by d9w** [comment]
This was resolved by 5d254ca. The leaderboard has been updated to include this commit.
