### ISSUE TITLE
Competition scenarios

### ISSUE THREAD

**Issue by mmayo888** [d9w/WindFLO#8]
Hi,

Quick request about the scenarios here:
https://github.com/d9w/WindFLO/tree/master/Wind%20Competition/2015/Scenarios

There were five scenarios given initially and then five new scenarios in the last week of the competition. Only five of them are in the github folder however. Could the additional five scenarios also be added?

Thanks
Mike

**Comment by d9w** [comment]
Now at https://github.com/d9w/WindFLO/blob/master/Wind%20Competition/2015/Scenarios/practice_0.xml
